#!/usr/bin/env python3
"""Sync per-company MQTT credentials + ACLs from AviSafe into mosquitto.

Polls the AviSafe edge function `mqtt-broker-credentials` (shared-secret auth)
and rewrites /mosquitto/data/passwd and /mosquitto/data/acl whenever anything
changed, then signals mosquitto (SIGHUP) to reload.

Each credential set may publish only on the serial numbers belonging to its
company group (own drones + drones the group is authorised to fly).

Environment / Fly secrets:
  AVISAFE_CREDENTIALS_URL   - https://<ref>.functions.supabase.co/mqtt-broker-credentials
  MQTT_BROKER_API_SECRET    - shared secret, sent as x-broker-secret
  CRED_SYNC_INTERVAL        - seconds between polls (default 60)
"""

import hashlib
import json
import logging
import os
import signal
import subprocess
import sys
import time

import requests

logging.basicConfig(
    level=os.environ.get("LOG_LEVEL", "INFO").upper(),
    stream=sys.stdout,
    format="%(asctime)s %(levelname)s [credsync] %(message)s",
)
log = logging.getLogger("credsync")

URL = (os.environ.get("AVISAFE_CREDENTIALS_URL") or "").strip()
SECRET = os.environ.get("MQTT_BROKER_API_SECRET") or ""
INTERVAL = int(os.environ.get("CRED_SYNC_INTERVAL", "60"))

PASSWD_FILE = "/mosquitto/data/passwd"
ACL_FILE = "/mosquitto/data/acl"

_last_hash = None


def fetch():
    resp = requests.get(URL, headers={"x-broker-secret": SECRET}, timeout=15)
    if resp.status_code >= 300:
        # The secret itself is never logged - only the status and a short body.
        log.error(
            "credential feed HTTP %s from %s body=%s",
            resp.status_code,
            URL,
            resp.text[:200],
        )
        resp.raise_for_status()
    return resp.json().get("credentials", [])


def write_passwd(creds):
    # The internal bridge user is always written first (-c resets the file),
    # then one entry per company credential set.
    entries = [
        (os.environ.get("MQTT_USERNAME", ""), os.environ.get("MQTT_PASSWORD", "")),
    ] + [(c["username"], c["password"]) for c in creds]

    first = True
    written = []
    for username, password in entries:
        if not username or not password:
            continue
        args = ["mosquitto_passwd", "-b"]
        if first:
            args.append("-c")
            first = False
        args += [PASSWD_FILE, username, password]
        subprocess.run(args, check=True)
        written.append(username)
    os.chmod(PASSWD_FILE, 0o600)
    log.info("passwd written with %d users: %s", len(written), ", ".join(written))


def write_acl(creds):
    lines = [
        "# generated by credsync.py - do not edit",
        "",
        "# internal bridge user: full access",
        "user %s" % os.environ.get("MQTT_USERNAME", "avisafe-bridge"),
        "topic readwrite #",
        "",
    ]
    for c in creds:
        lines.append("user %s" % c["username"])
        for sn in c.get("serial_numbers", []):
            lines.append("topic readwrite sys/product/%s/#" % sn)
            lines.append("topic readwrite thing/product/%s/#" % sn)
        lines.append("")
        log.info(
            "acl user=%s serials=%d companies=%d",
            c["username"],
            len(c.get("serial_numbers", [])),
            len(c.get("company_ids", [])),
        )
    with open(ACL_FILE, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    os.chmod(ACL_FILE, 0o600)


def reload_mosquitto():
    try:
        out = subprocess.run(["pgrep", "mosquitto"], capture_output=True, text=True)
        for pid in out.stdout.split():
            os.kill(int(pid), signal.SIGHUP)
            log.info("sent SIGHUP to mosquitto pid=%s", pid)
    except Exception as exc:  # noqa: BLE001
        log.warning("could not reload mosquitto: %s", exc)


def sync_once():
    global _last_hash
    creds = fetch()
    log.info(
        "sync attempt ok: fetched %d credential sets (%s)",
        len(creds),
        ", ".join(c.get("username", "?") for c in creds) or "none",
    )
    digest = hashlib.sha256(
        json.dumps(creds, sort_keys=True).encode("utf-8")
    ).hexdigest()
    if digest == _last_hash:
        log.info("no credential changes (%d sets)", len(creds))
        return
    if not creds:
        log.warning("credential feed returned 0 active sets - keeping current files")
        return
    write_passwd(creds)
    write_acl(creds)
    reload_mosquitto()
    _last_hash = digest
    log.info("applied %d credential sets", len(creds))


def main():
    if URL and SECRET:
        log.info(
            "credential sync configured: url=%s interval=%ds", URL, INTERVAL
        )
    while True:
        if not URL or not SECRET:
            # Repeated on every attempt on purpose - a single startup line
            # drowns in mosquitto's own logging.
            log.error(
                "ADVARSEL: credential sync is NOT configured "
                "(AVISAFE_CREDENTIALS_URL set=%s, MQTT_BROKER_API_SECRET set=%s). "
                "Only the internal bridge user can connect; customer FH2 Sync "
                "logins will be rejected as 'not authorised'.",
                bool(URL),
                bool(SECRET),
            )
        else:
            try:
                sync_once()
            except Exception as exc:  # noqa: BLE001
                log.error("sync failed: %s", exc)
        time.sleep(INTERVAL)


if __name__ == "__main__":
    main()
