#!/usr/bin/env python3
"""Sync per-company MQTT credentials + ACLs from AviSafe into mosquitto.

Polls the AviSafe edge function `mqtt-broker-credentials` (shared-secret auth)
and rewrites /mosquitto/data/passwd and /mosquitto/data/acl whenever anything
changed, then signals mosquitto (SIGHUP) to reload.

Each credential set may publish only on the serial numbers belonging to its
company group (own drones + drones the group is authorised to fly).

Environment / Fly secrets:
  AVISAFE_CREDENTIALS_URL   - https://<ref>.functions.supabase.co/mqtt-broker-credentials
  MQTT_BROKER_API_SECRET    - shared secret, sent as x-broker-secret
  CRED_SYNC_INTERVAL        - seconds between polls (default 60)
"""

import hashlib
import json
import logging
import os
import pwd
import shutil
import signal
import subprocess
import sys
import time

import requests

logging.basicConfig(
    level=os.environ.get("LOG_LEVEL", "INFO").upper(),
    stream=sys.stdout,
    format="%(asctime)s %(levelname)s [credsync] %(message)s",
)
log = logging.getLogger("credsync")

URL = (os.environ.get("AVISAFE_CREDENTIALS_URL") or "").strip()
SECRET = os.environ.get("MQTT_BROKER_API_SECRET") or ""
INTERVAL = int(os.environ.get("CRED_SYNC_INTERVAL", "60"))

PASSWD_FILE = "/mosquitto/data/passwd"
PASSWD_TMP = "/mosquitto/data/passwd.tmp"
PASSWD_BACKUP = "/mosquitto/data/passwd.previous"
ACL_FILE = "/mosquitto/data/acl"
ACL_TMP = "/mosquitto/data/acl.tmp"
ACL_BACKUP = "/mosquitto/data/acl.previous"
MOSQUITTO_UID = pwd.getpwnam("mosquitto").pw_uid
MOSQUITTO_GID = pwd.getpwnam("mosquitto").pw_gid

_last_hash = None


def fetch():
    resp = requests.get(URL, headers={"x-broker-secret": SECRET}, timeout=15)
    if resp.status_code >= 300:
        # The secret itself is never logged - only the status and a short body.
        log.error(
            "credential feed HTTP %s from %s body=%s",
            resp.status_code,
            URL,
            resp.text[:200],
        )
        resp.raise_for_status()
    return resp.json().get("credentials", [])


def write_passwd(creds):
    """Rebuild the whole password file from scratch, then swap it in atomically.

    Rebuilding (instead of appending) means credentials disabled in AviSafe
    actually disappear from the file. `-c` is never used on the live file: it
    fails on every run after the first ("File exists").
    """
    # The shared/internal user is written explicitly - it is still in active use.
    entries = [
        (os.environ.get("MQTT_USERNAME", ""), os.environ.get("MQTT_PASSWORD", "")),
    ] + [(c["username"], c["password"]) for c in creds]

    if os.path.exists(PASSWD_TMP):
        os.remove(PASSWD_TMP)
    # Create an empty temp file; mosquitto_passwd -b appends to an existing file.
    with open(PASSWD_TMP, "w"):
        pass
    os.chmod(PASSWD_TMP, 0o600)

    written = []
    for username, password in entries:
        if not username or not password:
            continue
        subprocess.run(
            ["mosquitto_passwd", "-b", PASSWD_TMP, username, password], check=True
        )
        written.append(username)

    with open(PASSWD_TMP, "rb") as fh:
        os.fsync(fh.fileno())

    log.info(
        "passwd rebuild: %d users staged in %s: %s",
        len(written),
        PASSWD_TMP,
        ", ".join(written),
    )

    # mosquitto drops privileges to its own user. A root-owned 0600 file looks
    # valid to credsync but cannot be reopened by mosquitto during SIGHUP.
    live = _install_verified_file(
        PASSWD_TMP, PASSWD_FILE, PASSWD_BACKUP, "password file"
    )
    log.info("passwd swapped in: %d lines now live", live)


def write_acl(creds):
    lines = [
        "# generated by credsync.py - do not edit",
        "",
        "# internal bridge user: full access",
        "user %s" % os.environ.get("MQTT_USERNAME", "avisafe-bridge"),
        "topic readwrite #",
        "",
    ]
    for c in creds:
        lines.append("user %s" % c["username"])
        for sn in c.get("serial_numbers", []):
            lines.append("topic readwrite sys/product/%s/#" % sn)
            lines.append("topic readwrite thing/product/%s/#" % sn)
        lines.append("")
        log.info(
            "acl user=%s serials=%d companies=%d",
            c["username"],
            len(c.get("serial_numbers", [])),
            len(c.get("company_ids", [])),
        )
    with open(ACL_TMP, "w") as fh:
        fh.write("\n".join(lines) + "\n")
        fh.flush()
        os.fsync(fh.fileno())
    _install_verified_file(ACL_TMP, ACL_FILE, ACL_BACKUP, "ACL file")


def _install_verified_file(staged_path, live_path, backup_path, label):
    """Install a staged auth file and restore the old one on any failure."""
    had_live_file = os.path.isfile(live_path) and os.path.getsize(live_path) > 0
    if had_live_file:
        shutil.copy2(live_path, backup_path)
        os.chown(backup_path, MOSQUITTO_UID, MOSQUITTO_GID)
        os.chmod(backup_path, 0o600)

    try:
        os.chown(staged_path, MOSQUITTO_UID, MOSQUITTO_GID)
        os.chmod(staged_path, 0o600)
        os.replace(staged_path, live_path)
        os.chown(live_path, MOSQUITTO_UID, MOSQUITTO_GID)
        os.chmod(live_path, 0o600)
        _sync_directory(live_path)
        return _verify_file(live_path, label)
    except Exception:
        if had_live_file and os.path.isfile(backup_path):
            os.replace(backup_path, live_path)
            os.chown(live_path, MOSQUITTO_UID, MOSQUITTO_GID)
            os.chmod(live_path, 0o600)
            _sync_directory(live_path)
            log.error("%s update failed; restored previous live file", label)
        raise
    finally:
        if os.path.exists(backup_path):
            os.remove(backup_path)


def _sync_directory(path):
    """Flush a renamed directory entry before mosquitto is asked to reload."""
    directory_fd = os.open(os.path.dirname(path), os.O_RDONLY)
    try:
        os.fsync(directory_fd)
    finally:
        os.close(directory_fd)


def _verify_file(path, label):
    """Require a stable, non-empty file readable by the mosquitto user."""
    if not os.path.isfile(path) or os.path.getsize(path) <= 0:
        raise RuntimeError(f"{label} is missing or empty after swap: {path}")

    stat_result = os.stat(path)
    if stat_result.st_uid != MOSQUITTO_UID or stat_result.st_gid != MOSQUITTO_GID:
        raise RuntimeError(f"{label} has incorrect owner after swap: {path}")

    with open(path, "rb") as fh:
        content = fh.read()
    if not content.strip():
        raise RuntimeError(f"{label} contains no usable data after swap: {path}")
    return len([line for line in content.splitlines() if line.strip()])


def auth_files_ready():
    _verify_file(PASSWD_FILE, "password file")
    _verify_file(ACL_FILE, "ACL file")


def reload_mosquitto():
    # Fly volumes may expose a just-renamed directory entry with a short delay.
    # Validate twice and never signal mosquitto if either check fails.
    auth_files_ready()
    time.sleep(0.1)
    auth_files_ready()

    out = subprocess.run(
        ["pgrep", "mosquitto"], capture_output=True, text=True, check=False
    )
    pids = out.stdout.split()
    if not pids:
        raise RuntimeError("no running mosquitto process found; SIGHUP not sent")
    for pid in pids:
        os.kill(int(pid), signal.SIGHUP)
        log.info("sent SIGHUP to mosquitto pid=%s after two successful file checks", pid)


def sync_once():
    global _last_hash
    creds = fetch()
    log.info(
        "sync attempt ok: fetched %d credential sets (%s)",
        len(creds),
        ", ".join(c.get("username", "?") for c in creds) or "none",
    )
    digest = hashlib.sha256(
        json.dumps(creds, sort_keys=True).encode("utf-8")
    ).hexdigest()
    if digest == _last_hash:
        log.info("no credential changes (%d sets)", len(creds))
        return
    if not creds:
        log.warning("credential feed returned 0 active sets - keeping current files")
        return
    try:
        write_passwd(creds)
        write_acl(creds)
        reload_mosquitto()
    except Exception as exc:  # noqa: BLE001
        # Most importantly, do not send SIGHUP after a failed write/validation.
        # Mosquitto keeps serving with the credentials already loaded in memory.
        log.error("credential reload aborted; mosquitto was left running: %s", exc)
        return
    _last_hash = digest
    log.info("applied %d credential sets", len(creds))


def main():
    if URL and SECRET:
        log.info(
            "credential sync configured: url=%s interval=%ds", URL, INTERVAL
        )
    while True:
        if not URL or not SECRET:
            # Repeated on every attempt on purpose - a single startup line
            # drowns in mosquitto's own logging.
            log.error(
                "ADVARSEL: credential sync is NOT configured "
                "(AVISAFE_CREDENTIALS_URL set=%s, MQTT_BROKER_API_SECRET set=%s). "
                "Only the internal bridge user can connect; customer FH2 Sync "
                "logins will be rejected as 'not authorised'.",
                bool(URL),
                bool(SECRET),
            )
        else:
            try:
                sync_once()
            except Exception as exc:  # noqa: BLE001
                log.error("sync failed: %s", exc)
        time.sleep(INTERVAL)


if __name__ == "__main__":
    main()
