app = "mqtt-broker-avisafe"
primary_region = "ams"

[[services]]
  protocol = "tcp"
  internal_port = 1883

  [[services.ports]]
    port = 1883
    handlers = []

  [[services.ports]]
    port = 8883
    handlers = ["tls"]

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1